---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2018/3/29 14:48
---
function random(n,m)
    --思路是用随机结构放大处理以后再置随机种子，然后随机
    math.randomseed(os.clock()*math.random(1000000,90000000)+math.random(1000000,9000000)+tonumber(tostring(os.time()):reverse():sub(1, 6))+os.time())
    --math.randomseed(tonumber(tostring(os.time()):reverse():sub(1, 6)))
    return math.random(n,m)
end
--[[function randomNumber(len)--len是随机多长
    local rt = ""
    for i = 1, len do
        if i==1 then --让第一个数不是0
            rt = rt..random(1,9);
        else
            rt = rt..random(0,9)
        end
    end
    return rt
end
function randomLetter(len)
    local rt = ""
    for i = 1, len do
        rt = rt..string.char(random(97,122))
    end
    return rt
end
function randomCapital(len)
    local rt = ""
    for i = 1, len do
        rt = rt..string.char(random(65,90))
    end
    return rt
end]]

--[[
for i = 1, 5 do
    print(randomCapital(12))
end]]
-- 首先定一个随机模式表，相当于枚举
RDModle ={
    RSM_Capital = 1 , --纯大写字母
    RSM_Letter = 2 , --纯小写字母
    RSM_Cap_Let = 3 , --大小写
    RSM_Number = 4 , --纯数字
    RSM_Cap_Num = 5 , --大写字母+数字
    RSM_Let_Num = 6 , --小写字母+数字
    RSM_All = 7  --全部
}
function RandomString(len,modl) --产生一组指定长度的随机文本模式
    local BC = "ABCDEFGHJKLMNPQRSTUVWXYZ" --1
    local SC = "abcdefghijklmnopqrstuvwxyz"--2
    local NO = "23456789"--4
    local maxLen = 0
    local templete = ""
    if modl == nil or modl == RDModle.RSM_Capital then
        templete = BC  --如果没有写参数 默认纯大写
        maxLen = 26
    elseif modl == RDModle.RSM_Letter then
        templete = SC  --纯小写
        maxLen = 26
    elseif modl == RDModle.RSM_Cap_Let then
        templete = SC..BC  --大小写
        maxLen = 52
    elseif modl == RDModle.RSM_Number then
        templete = NO  --如纯数字
        maxLen = 10
    elseif modl == RDModle.RSM_Cap_Num then
        templete = NO..BC  --大写+数字
        maxLen = 32
    elseif modl == RDModle.RSM_Let_Num then
        templete = NO..SC  --小写+数字
        maxLen = 36
    elseif modl == RDModle.RSM_All then
        templete = NO..SC..BC  --大小写+数字
        maxLen = 62
    else
        templete = NO  --如果写了参数 但是不正确 默认纯数字
        maxLen = 10
    end

    --分析完模式参数，开始随机部分
    local srt = {}
    for i = 1, len do
        local index = random(1,maxLen)
        srt[i] = string.sub(templete , index , index)
    end
    return table.concat(srt,"")
end
for i = 1, 10 do
    print(RandomString(14,5))
end


local test;