---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2018/3/29 15:26
---
local b = {}
local systime = os.time() --时间
local mark = 0
local k = 1
local N = 8--生成随机数的数量
math.randomseed(tostring(systime):reverse():sub(1, 6))
b[1] = math.random(1, 25)
print("trueMark:" .. mark .. "trueNumber" .. b[1])
while table.maxn(b) < N do
    local c = math.random(1, 25)
    for i = 1, table.maxn(b) do
        if c == b[i] then
            mark = 2
            break
        else
            mark = 1
        end
    end
    if mark == 1 then
        print("trueMark:" .. mark .. "trueNumber" .. c)
        k = k + 1
        b[k] = c
    else
        systime = systime + 1
        math.randomseed(tostring(systime):reverse():sub(1, 6))
    end
end